learningParams:
    seed: 1299777356020
    minValue: 0
    maxValue: 300
    minTraceLength: 6
    maxTraceLength: 6
    maxNumTraces: 10000
    sutInterface: sutinfo.yaml
    mapper: simple_3
    yanCommand: /home/student/yannakakis2/build/main
    nonDeterminismTestIterations: 20
tcpParams:
    sutPort: 18200
    sutIP: 127.0.0.1
    oracle: client


