learningParams:
    seed: 1299777356020
    minValue: 0
    maxValue: 300
    minTraceLength: 6
    maxTraceLength: 6
    maxNumTraces: 100000
    sutInterface: sutinfo.yaml
    yanCommand: /home/paul/Yannakakis/main
    mapper: java
    testTraces:
     - ["CLOSE", "LISTEN", "SYN(V,V,0)"]
     - ["LISTEN", "SYN(V,V,0)", "ACK+PSH(V,V,1)", "ACCEPT", "SEND", "FIN+ACK(V,V,0)", "CLOSECONNECTION"]
     - ["LISTEN", "ACCEPT", "SYN(V,V,0)", "ACK+PSH(V,V,1)", "CLOSECONNECTION"]
     - ["LISTEN", "SYN(V,V,0)", "ACK(V,V,0)", "ACK+PSH(V,V,1)", "SYN+ACK(V,V,0)", "ACCEPT", "LISTEN", "SYN(V,V,0)"]
     - ["LISTEN", "ACCEPT", "SYN(V,V,0)", "ACK(V,V,0)", "ACK+PSH(V,V,1)", "SYN+ACK(V,V,0)", "ACCEPT", "SYN(V,V,0)", "ACK+PSH(V,V,1)", "CLOSECONNECTION"]
     - ["LISTEN", "ACCEPT", "SYN(V,V,0)", "ACK(V,V,0)", "ACK+PSH(V,V,1)", "FIN+ACK(V,V,0)", "ACK+RST(V,V,0)", "SYN(V,V,0)", "ACK+PSH(V,V,1)", "CLOSECONNECTION", "ACCEPT", "CLOSECONNECTION"]
     - ["LISTEN", "ACCEPT", "SYN(V,V,0)", "ACK(V,V,0)", "ACK+PSH(V,V,1)", "SYN+ACK(V,V,0)", "ACCEPT", "SYN(V,V,0)", "ACK+PSH(V,V,1)", "CLOSECONNECTION"]
     - ["LISTEN", "ACCEPT", "SYN(V,V,0)", "ACK(V,V,0)", "ACK+PSH(V,V,1)", "SYN+ACK(V,V,0)", "ACCEPT", "SYN(V,V,0)", "ACK+PSH(V,V,1)", "CLOSECONNECTION", "ACCEPT", "CLOSECONNECTION"]
     - ["LISTEN", "SYN(V,V,0)", "ACK(V,V,0)", "ACK+PSH(V,V,1)", "CLOSECONNECTION", "SYN+ACK(V,V,0)"] 
tcpParams:
    sutPort: 18200
    sutIP: 127.0.0.1
    oracle: client
