learning:
    sutinfoFile: "sutinfo.yaml"
    seed: 1299777356020
    minValue: 0
    maxValue: 300
    preferFirst: true
testing:
    minTraceLength: 5
    maxTraceLength: 5
    maxNumTraces: 100
tcp:
    cacheFile: "cache.txt"
    verbose: true